---

# Clair
clair_image_tag: v3.0.4

# Clair-Quay SSL Trust
clair_ssl_trust_src_file: /tmp/clair-ssl-trust.crt
clair_ssl_trust_configure: False

# Quay address
quay_enterprise_address: https://myregistry.mycompany.com

postgresql_db_uri: "postgresql://{{ clair_database_username }}:{{ clair_database_password }}@{{ postgresql_host if postgresql_host is defined and postgresql_host|trim != '' else hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}:{{ postgresql_port | default('5432') }}/{{ clair_database_name | default('clair') }}{{ '?sslmode=disable' if not postgresql_ssl_enabled }}"